apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
    name: zk-{{ .Values.name }}-pdb
spec:
    selector:
        matchLabels:
            app: zk-{{ .Values.name }}
    maxUnavailable: 1