apiVersion: v1
kind: Service
metadata:
    name: zk-{{ .Values.name }}
    labels:
        app: zk-{{ .Values.name }}
spec:
    ports:
        - port: 2181
          name: client
    selector:
        app: zk-{{ .Values.name }}