apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: zk-{{ .Values.name }}
spec:
    selector:
        matchLabels:
            app: zk-{{ .Values.name }}
    serviceName: zk-{{ .Values.name }}
    replicas: 3
    podManagementPolicy: Parallel
    updateStrategy:
        type: RollingUpdate
    template:
        metadata:
            labels:
                app: zk-{{ .Values.name }}
        spec:
          {{ if .Values.enablePodAffinity }}
            affinity:
                podAntiAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                        - labelSelector:
                              matchExpressions:
                                  - key: "app"
                                    operator: In
                                    values:
                                        - zk-{{ .Values.name }}
                          topologyKey: "kubernetes.io/hostname"
          {{- end }}
            containers:
                - name: zookeeper-server
                  image: goharbor.ebsig.com/library/apache/zookeeper:1.0-3.4.10
                  resources:
                      requests:
                          memory: 100Mi
                          cpu: 10m
                      limits:
                          memory: 2Gi
                          cpu: 2000m
                  ports:
                      - containerPort: 2181
                        name: client
                      - containerPort: 2888
                        name: server
                      - containerPort: 3888
                        name: leader-election
                  command:
                      - sh
                      - -c
                      - "start-zookeeper \
                          --servers=3 \
                          --data_dir=/var/lib/zookeeper/data \
                          --data_log_dir=/var/lib/zookeeper/data/log \
                          --conf_dir=/opt/zookeeper/conf \
                          --client_port=2181 \
                          --election_port=3888 \
                          --server_port=2888 \
                          --tick_time=2000 \
                          --init_limit=10 \
                          --sync_limit=5 \
                          --heap=512M \
                          --max_client_cnxns=60 \
                          --snap_retain_count=3 \
                          --purge_interval=12 \
                          --max_session_timeout=40000 \
                          --min_session_timeout=4000 \
                          --log_level=INFO"
                  readinessProbe:
                      exec:
                          command:
                              - sh
                              - -c
                              - "zookeeper-ready 2181"
                      initialDelaySeconds: 10
                      timeoutSeconds: 5
                  livenessProbe:
                      exec:
                          command:
                              - sh
                              - -c
                              - "zookeeper-ready 2181"
                      initialDelaySeconds: 10
                      timeoutSeconds: 5
                  volumeMounts:
                      - name: zk-data
                        mountPath: /var/lib/zookeeper/data
                        subPath: logs
            securityContext:
                runAsUser: 1000
                fsGroup: 1000
    volumeClaimTemplates:
        - metadata:
              name: zk-data
              annotations:
                  volume.beta.kubernetes.io/storage-class: {{ .Values.storageClass }}
          spec:
              accessModes:
                  - ReadWriteOnce
              resources:
                  requests:
                      storage: {{ .Values.storageCapacity }}