apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
    name: kafka-{{ .Values.kafka.name }}-pdb
spec:
    selector:
        matchLabels:
            app: kafka-{{ .Values.kafka.name }}
    maxUnavailable: 1