apiVersion: v1
kind: Service
metadata:
    name: kafka-{{ .Values.kafka.name }}
    labels:
        app: kafka-{{ .Values.kafka.name }}
spec:
    ports:
        - port: 9093
          name: server
    selector:
        app: kafka-{{ .Values.kafka.name }}