apiVersion: v1
kind: ConfigMap
metadata:
    name: cm-mysql-{{ .Values.mysql.name }}
    labels:
        app: mysql-{{ .Values.mysql.name }}
data:
    my.cnf: |
        [mysqld]
        datadir=/var/lib/mysql/data
        socket=/var/lib/mysql/mysql.sock
        pid-file=/var/run/mysqld/mysqld.pid
        default_authentication_plugin = mysql_native_password
        character-set-server=utf8
        collation-server=utf8_general_ci
        default-storage-engine=InnoDB
        skip-external-locking
        skip-name-resolve
        super-large-pages

        max-prepared-stmt-count=100000
        max_connect_errors = 5000
        max_connections=5000
        connect_timeout = 10
        innodb_log_files_in_group = 3
        innodb_open_files=1000
        innodb_strict_mode = 1
        innodb_io_capacity=600
        innodb_lock_wait_timeout=30
        innodb_table_locks=0
        slave-net-timeout = 15
        wait_timeout=3600

        performance_schema=ON
        sql_mode = {{ .Values.mysql.config.sql_mode }}
        innodb_buffer_pool_instances    = {{ .Values.mysql.config.buffer_pool_instance }}
        innodb_buffer_pool_size         =  {{ .Values.mysql.config.buffer_pool_size }}
        innodb_file_per_table           = 1
        innodb_flush_log_at_trx_commit  = 0
        innodb_flush_method             = O_DIRECT
        innodb_log_buffer_size          = 16M
        innodb_log_file_size            = 512M
        innodb_stats_on_metadata        = 0
        innodb_thread_concurrency      	= 0
        innodb_purge_threads           	= 1
        innodb_read_io_threads          = 8
        innodb_write_io_threads         = 8


        back_log                        = 2048
        thread_cache_size               = 64
        thread_stack                    = 256K


        join_buffer_size                = 8M
        read_buffer_size                = 8M
        read_rnd_buffer_size            = 8M
        sort_buffer_size                = 8M

        table_definition_cache          = 40000
        table_open_cache                = 40000
        open_files_limit = 65535
        max_heap_table_size             = 128M
        tmp_table_size                  = 128M
        max_allowed_packet              = 4M

        transaction_isolation = REPEATABLE-READ


        log_queries_not_using_indexes   = 0
        long_query_time                 = 2
        slow_query_log                  = 1
        slow_query_log_file             = /var/lib/mysql/mysql_slow.log

        [mysqldump]
        quick
        quote_names
        max_allowed_packet              = 256M
        [mysql]
        local-infile=1
