apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-{{ .Values.mysql.name }}
  labels:
    app: mysql-{{ .Values.mysql.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-{{ .Values.mysql.name }}
  template:
    metadata:
      labels:
        app: mysql-{{ .Values.mysql.name }}
    spec:
      containers:
      - name: mysql-{{ .Values.mysql.name }}
        image: {{ .Values.mysql.image }}
        securityContext:
           runAsUser: 0
        env:
            -   name: MYSQL_ROOT_PASSWORD
                value: {{ .Values.mysql.config.password }}
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - mountPath: /var/lib/mysql/data
          name: mysql-data
        - mountPath: /etc/mysql/conf.d
          readOnly: true
          name: mysql-cnf
        resources:
            requests:
                cpu: {{ .Values.mysql.resources.requests.cpu }}
                memory: {{ .Values.mysql.resources.requests.memory }}
            limits:
                cpu: {{ .Values.mysql.resources.limits.cpu }}
                memory: {{ .Values.mysql.resources.limits.memory }}
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
              claimName: pvc-mysql-{{ .Values.mysql.name}}
        - name: mysql-cnf
          configMap:
              name: cm-mysql-{{ .Values.mysql.name }}
