apiVersion: v1
kind: Service
metadata:
 name: mysql-{{ .Values.mysql.name }}
 labels:
     app: mysql-{{ .Values.mysql.name }}
spec:
  selector:
    app: mysql-{{ .Values.mysql.name }}
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306