apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-{{ .Values.redis.name }}
  labels:
    app: redis-{{ .Values.redis.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-{{ .Values.redis.name }}
  template:
    metadata:
      labels:
        app: redis-{{ .Values.redis.name }}
    spec:
      containers:
      - name: redis-{{ .Values.redis.name }}
        image: {{ .Values.redis.image }}
        command:
        - "redis-server"
        - "/etc/config/redis.conf"
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /data
          name: redis-persistent-data
        - mountPath: /etc/config
          readOnly: true
          name: redis-conf
        resources:
            requests:
                cpu: 10m
                memory: 10Mi
            limits:
                cpu: 1000m
                memory: 2000Mi
      volumes:
        - name: redis-persistent-data
          persistentVolumeClaim:
              claimName: pvc-redis-{{ .Values.redis.name}}
        - name: redis-conf
          configMap:
              name: cm-redis-{{ .Values.redis.name }}