apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: pvc-redis-{{ .Values.redis.name }}
    labels:
        app: redis-{{ .Values.redis.name }}
spec:
    storageClassName: {{ .Values.redis.storageClass }}
    accessModes:
        -   ReadWriteOnce
    resources:
        requests:
            storage: {{ .Values.redis.storageCapacity }}