apiVersion: v1
kind: Service
metadata:
 name: redis-{{ .Values.redis.name }}
 labels:
     app: redis-{{ .Values.redis.name }}
spec:
  selector:
    app: redis-{{ .Values.redis.name }}
  ports:
  - name: redis
    port: 6379
    targetPort: 6379