{{ if .Values.mongo.auth.enable }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: mongo-keyfile-{{ .Values.mongo.name }}
    labels:
        app: mongo-keyfile-{{ .Values.mongo.name }}
data:
    mongodb-keyfile: {{ randAlphaNum 600 | b64enc  }}
  {{ end }}