apiVersion: v1
kind: Service
metadata:
  name: mongo-{{ .Values.mongo.name }}
  labels:
    app: mongo-{{ .Values.mongo.name }}
spec:
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongo-port
  clusterIP: None
  selector:
    app: mongo-{{ .Values.mongo.name }}